### ISSUE TITLE
 React  dependency is missing in CLJS dev profile

### ISSUE THREAD

**Issue by xperian** [matthiasn/BirdWatch#30]
This works. 
```
{:id "dev"
                        :source-paths ["src/cljs"]
                        :compiler {:output-to "resources/public/js/build/birdwatch.js"
                                   :output-dir "resources/public/js/build/out"
                                   :optimizations :simple
                                   :preamble ["reagent/react.js"]
                                   :source-map "resources/public/js/build/birdwatch.js.map"
                                   :externs ["externs/misc.js"]
                                   }}
```

**Comment by matthiasn** [comment]
Thanks. The /dev route also didn't work previously as I hadn't used that in a while. Fixed as well.

**Comment by xperian** [comment]
And there is an file name inconsistency in TwitterClient . 
https://github.com/matthiasn/BirdWatch/blob/master/Clojure-Websockets/TwitterClient/src/clj/birdwatch_tc/main.clj
```
(def conf (edn/read-string (slurp "twitterconf.edn")))
```

I think this should be twitterconf-tpl.edn or otherwise.

**Comment by matthiasn** [comment]
No that's actually intended. The ````twitterconf-tpl.edn```` is intended to be the template that you copy to ````twitterconf.edn```` and then fill out with your Twitter dev credentials. This file is then ignored by git so you don't have to check in sensitive information.

**Comment by xperian** [comment]
Thanks ， got it
