### ISSUE TITLE
Change listen address 

### ISSUE THREAD

**Issue by Keithsc** [matthiasn/BirdWatch#34]
Hi, I have managed to install and start both the client and server on my Centos7 server but I can't figure out how to change the listen address from 127.0.0.1:8888 to either myip:8888 or 0.0.0.0:8888 !

I am starting the server with "lein run",  can you help ?

Thanks
Keith.

**Comment by matthiasn** [comment]
Sure! All you need to do is define environment variables for that. You could for example call the application like this:

    HOST=myip PORT=8889 lein run
