### ISSUE TITLE
Is it still working code ?

### ISSUE THREAD

**Issue by MyraBaba** [matthiasn/BirdWatch#35]
Hi matthiasn,

Is this code still working ?

and I wonder what is the latest language you are in love ? still clojure?

**Comment by matthiasn** [comment]
Hey, yes it's still working and running as a [live demo](http://birdwatch.matthiasnehlsen.com). There's some refactoring under way towards using re-frame, like in my other applications. But whatever is there works fine as of today. Yup Clojure is great, best choice as far as programming languages go, IMHO.
